//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.20 at 06:00:41 PM EDT 
//


package edu.cmu.mse.aes.project1.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="saddle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seatpost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="handlebars" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brakeset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saddle",
    "seatpost",
    "handlebars",
    "stem",
    "headset",
    "brakeset"
})
@XmlRootElement(name = "componentinfo")
public class Componentinfo {

    @XmlElement(required = true)
    protected String saddle;
    @XmlElement(required = true)
    protected String seatpost;
    @XmlElement(required = true)
    protected String handlebars;
    @XmlElement(required = true)
    protected String stem;
    @XmlElement(required = true)
    protected String headset;
    @XmlElement(required = true)
    protected String brakeset;

    /**
     * Gets the value of the saddle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaddle() {
        return saddle;
    }

    /**
     * Sets the value of the saddle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaddle(String value) {
        this.saddle = value;
    }

    /**
     * Gets the value of the seatpost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatpost() {
        return seatpost;
    }

    /**
     * Sets the value of the seatpost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatpost(String value) {
        this.seatpost = value;
    }

    /**
     * Gets the value of the handlebars property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandlebars() {
        return handlebars;
    }

    /**
     * Sets the value of the handlebars property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandlebars(String value) {
        this.handlebars = value;
    }

    /**
     * Gets the value of the stem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStem() {
        return stem;
    }

    /**
     * Sets the value of the stem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStem(String value) {
        this.stem = value;
    }

    /**
     * Gets the value of the headset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadset() {
        return headset;
    }

    /**
     * Sets the value of the headset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadset(String value) {
        this.headset = value;
    }

    /**
     * Gets the value of the brakeset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrakeset() {
        return brakeset;
    }

    /**
     * Sets the value of the brakeset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrakeset(String value) {
        this.brakeset = value;
    }

}
